### Variables
@baseUrl = http://localhost:8080
@contentType = application/json

### Player IDs from sample data
@gamerPro123 = 750e8400-e29b-41d4-a716-446655440001
@chessMaster = 750e8400-e29b-41d4-a716-446655440002
@speedyGonzales = 750e8400-e29b-41d4-a716-446655440003
@puzzleWizard = 750e8400-e29b-41d4-a716-446655440004
@battleKnight = 750e8400-e29b-41d4-a716-446655440005
@casualGamer = 750e8400-e29b-41d4-a716-446655440006

### Game IDs from sample data
@chessMasterGame = 550e8400-e29b-41d4-a716-446655440001
@speedRacer = 550e8400-e29b-41d4-a716-446655440002
@puzzleQuest = 550e8400-e29b-41d4-a716-446655440003
@battleArena = 550e8400-e29b-41d4-a716-446655440004
@memoryCards = 550e8400-e29b-41d4-a716-446655440005

###############################################################################
### 1. Successful Purchase - CasualGamer buys Puzzle Quest (9.99 EUR)
###############################################################################
POST {{baseUrl}}/api/payments/initiate-purchase
Content-Type: {{contentType}}

{
  "playerId": "{{chessMaster}}",
  "gameId": "{{speedRacer}}"
}

####
POST {{baseUrl}}/api/payments/webhook
Content-Type: {{contentType}}

{
  "id": "evt_chessMaster_speedRacer",
  "object": "event",
  "type": "payment_intent.succeeded",
  "data": {
    "object": {
      "id": "pi_3SeZTrE4TIKVK4RK0CvTeNwK",
      "object": "payment_intent",
      "amount": 999,
      "amount_capturable": 0,
      "amount_received": 999,
      "currency": "eur",
      "status": "succeeded",
      "livemode": false,
      "created": 1765655311,
      "metadata": {
        "playerId": "750e8400-e29b-41d4-a716-446655440002",
        "gameId": "550e8400-e29b-41d4-a716-446655440002"
      }
    }
  }
}

###

- payment intent.succeeded only works with this :

# curl https://api.stripe.com/v1/payment_intents/pi_3SeZTrE4TIKVK4RK0CvTeNwK/confirm
#  -u sk_test_51SdsrVE4TIKVK4RKw97CEzYUR9KhwPpxNvDB44VqzDc7poc1bRpWRM66xn35tqCoVf90lSQjRQbFfc9qZXjaCL1u00LZEhRdQc:
#  -d "payment_method=pm_card_visa"
#  -d "return_url=https://talk-economic-rebates-stretch.trycloudflare.com/checkout/success"
